version: '3'
services:

  test_pg_jsonschema:
    container_name: pg_jsonschema_test
    build:
        context: ..
        dockerfile: ../Dockerfile
    environment:
      USER: postgres
    command:
      - cargo
      - pgrx
      - test
      - pg14
